[project]
name = "Stacks-Maritime-Trading"
authors = []
description = ""
telemetry_copy_on_to_cpu = false
boot_contracts = ["costs-v2", "pox-4", "lockup"]
[repl]
costs_version = 2
parser_version = 2
[repl.analysis]
passes = ["check_checker"]
[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[networks.devnet]
epoch = "3.3"
clarity_version = 4
